export const hotelTypes = [
  "Budget",
  "Boutique",
  "Luxury",
  "Ski Resort",
  "Business",
  "Romantic",
  "Family",
  "Hiking Resort",
  "Cabin",
  "Beach Resort",
  "Golf Resort",
  "Motel",
  "All Inclusive",
  "Pet Friendly",
  "Self Catering",
  "Pet Island",
  "Weed Resort",
];

export const hotelFacilities = [
  "Free Wifi",
  "Parking",
  "Airport Shuttle",
  "Family Room",
  "Non-Smoking Rooms",
  "Smoking Rooms",
  "Outdoor Pool",
  "Spa",
  "Fitness Center",
];
